Организовать структуру сервера. Вынести routes из App.
06-turin/gamedev pull request #105
Opened 2021-07-26 14:38 UTC by vicpril

Вынес посредников и контроллер в отдельные сущности, в разные файлы.
Вынес конфигурацию роутов из App.tsx в routes/index.ts. 
Создал компонент AppRoute для логики роутов внутри приложения.
Добавил асинхронную обработку методов роутов `fetchData` в посредник стора.

2021-07-27 18:27 UTC, jasper7466 approved these changes

2021-07-28 03:43 UTC, Marat5 requested changes
Все супер) Но посмотри комменты, они мелкие, поотвечай, если нет времени править - зови меня поставлю апрув)

2021-07-28 03:43 UTC, Marat5 commented on src/components/organisms/routes/AppRoute.tsx
> +        ? <PrivateRoute key={routeProps.path} {...routeProps} {...privateRoute} />
Давай оставим один компонент роута и не будем вкладывать их друг в друга? В обоих логики совсем немножко, надо её просто объединить

2021-07-28 03:43 UTC, Marat5 commented on src/components/organisms/routes/AppRoute.tsx
> +        ? <PrivateRoute key={routeProps.path} {...routeProps} {...privateRoute} />
вместо privateRoute можно назвать этот аргумент authBasedRedirect, а логику из прайват роут описать внутри AppRoute. Мне кажется так станет гораздо чище, а то сейчас не супер понятно. Если нет времени, то забей, я потом сделаю)

2021-07-28 03:43 UTC, Marat5 commented on src/server/index.d.ts
> +            store: ReturnType<typeof store>,
Ты уверен, что класть стор в ответ, чтобы передать его следующим мидлварам - норм практика? Может надо его экспортировать при создании? Хотя для каждого ответа он новый, так что наверное ты правильно делаешь. @DmitryKhitrin подскажи пожалуйста

2021-07-28 03:43 UTC, Marat5 commented on src/server/server.ts
> +app.get(['/*'], webpackMiddlewares(config), IndexController.renderApp);
Вебпак мидлвары тоже тогда наверное надо через use как остальные подключить, а тут только рендер апп оставить)

2021-07-28 03:43 UTC, Marat5 commented on src/components/organisms/App/App.tsx
> +          routes.map(({ fetchData, ...routeProps }) => <AppRoute key={routeProps.path} {...routeProps} />)
А зачем тут fetchData, если она не используется дальше? Если убрать фетчдату, то ругаться компилятор не будет

2021-07-28 07:40 UTC, DmitryKhitrin commented on src/server/index.d.ts
> +            store: ReturnType<typeof store>,
Мжду мидлварами мы оперируем просто данными, store создаем только в последний момент

2021-07-28 12:23 UTC, vicpril commented on src/components/organisms/App/App.tsx
> +          routes.map(({ fetchData, ...routeProps }) => <AppRoute key={routeProps.path} {...routeProps} />)
Метод fetchData используется только в посреднике хранилища, в основном чтобы диспатчить перед рендером. В компоненте роутов этот метод не нужен, поэтому я его убираю из routeProps.
В проекте от Моргунова такой же по.ход

2021-07-28 12:23 UTC, vicpril commented on src/server/server.ts
> +app.get(['/*'], webpackMiddlewares(config), IndexController.renderApp);
Ок, Это тоже будет работать.

2021-07-28 12:27 UTC, vicpril commented on src/server/index.d.ts
> +            store: ReturnType<typeof store>,
> Мжду мидлварами мы оперируем просто данными, store создаем только в последний момент

Вот тут не соглашусь, между инициализаций хранилища и методом контроллера могут быть посредники, которые работают с состоянием хранилища. Например, посредник, устанавливающий глобальное состояние авторизации, почему бы и нет? Ему уже нужен стор и он выполняется до метода контроллера.

2021-07-28 13:00 UTC, vicpril commented on src/components/organisms/routes/AppRoute.tsx
> +        ? <PrivateRoute key={routeProps.path} {...routeProps} {...privateRoute} />
Подожди, давай не будем забивать - давай обсуждать с аргументами)
Вот мои аргументы:
**1. Про компоненты**
Когда я пишу компоненты, я считаю это похожим на ООП, следовательно я стараюсь пользоваться принципами SOLID, а именно: 

- SRP - Принцип единственной ответственности - Для каждого класса должно быть определено единственное назначение.
- ISP - Принцип разделения интерфейса - много интерфейсов, специально предназначенных для клиентов лучше, чем один интерфейс общего назначения.

Грубо говоря, я буду дробить логику на сущности **везде, где это оправдано**. В данном случае:

- Компонент **AppRoute** - отвечает за определение типа роута для каждой страницы **приложения**: обычный (сущность Route), либо имеющий редирект по условию (сущность PrivateRoute). Все. Я не буду писать суда логику редиректа, потому что SRP. _Добавил сюда только ErrorBoundary, но и его можно вынести при желании._
- Компонент **PrivateRoute** - отвечает за логику редиректа. Он не должен проверять есть ли у страницы параметр или нет. Он должен получить параметры -> проверить условие -> сделать редирект. 

Все, чем проще, тем мне лучше.

**2. Про нейминг**
Я называю свойства, чтобы они были **просты** и **ассоциативно понятны**.
Вот у меня уже есть компонент PrivateRoute, который отвечает за редирект. Я буду называть свойства конфигов, которые пойдут в этот компонент примерно так же:  _privateRoute_ или _hasPrivateRoute_ или что-то вроде. Читая список роутов, я понимаю куда должен пойти этот конфиг. 
Если я назову это _authBasedRedirect_, потом я еще поломаю голову какое-то время - что такое Based, и если это только Based, то где конфиг для advanced или extended т.д.

PS: Марат, я не понял аргументов "логики совсем немножко" и "кажется так станет гораздо чище". Но я постарался описать, что у меня в голове, когда я пишу. Ты можешь поподробнее объяснить, что ты имел ввиду?

2021-07-28 13:40 UTC, DmitryKhitrin commented on src/server/index.d.ts
> +            store: ReturnType<typeof store>,
Это все можно передать в store в initialState

2021-07-29 00:15 UTC, Marat5 commented on src/components/organisms/routes/AppRoute.tsx
> +        ? <PrivateRoute key={routeProps.path} {...routeProps} {...privateRoute} />
ответил в треде в слаке) Хорошо что ты туда перенес)

2021-07-29 00:20 UTC, Marat5 commented on src/components/organisms/App/App.tsx
> +          routes.map(({ fetchData, ...routeProps }) => <AppRoute key={routeProps.path} {...routeProps} />)
Ааа, я понял тебя) Напиши это в коммент пожалуйста, а то это вообще не очевидно) Но идея по-моему отличная

2021-07-29 10:26 UTC, vicpril commented on src/server/index.d.ts
> +            store: ReturnType<typeof store>,
Ок

2021-07-30 10:34 UTC, Marat5 approved these changes
Апрув, но посмотри пожалуйста комменты) В основном вопросы, но есть и мини-правочки

2021-07-30 10:34 UTC, Marat5 commented on src/components/organisms/App/App.tsx
> +        {// Метод fetchData используется только в посреднике хранилища, в основном чтобы диспатчить перед рендером.
Глупый вопрос - "посредник" это мидлвар? Просто "мидлвара хранилища" это, например, thunk

2021-07-30 10:34 UTC, Marat5 commented on src/routes/index.ts
> +    // темка будет темная - т.к. еще есть глобальный тестовый переключатель - testDispatchMiddleware.ts
Когда что-то выпиливаешь лучше проходиться поиском по проекту, чтобы проверить, что это нигде не упоминается))

2021-07-30 10:34 UTC, Marat5 commented on src/server/controllers/IndexController.tsx
> +        url.parse(location).pathname as string,
'url.parse' is deprecated вскод говорит)
Тут просто сравнивается путь роута с путем из локейшн, и проверяется что в роуте есть фетчдата, я правильно понял?

2021-07-30 10:34 UTC, Marat5 commented on src/server/controllers/IndexController.tsx
> +    // dispatch action END to close saga
Опять сага пытается превратить наши комменты в бесполезный текст))

2021-07-30 10:34 UTC, Marat5 commented on src/server/index.d.ts
> +            logger: () => void;
Что-то я больше нигде не вижу logger) если убрать этот файл - что-то сломается?

2021-07-30 10:34 UTC, Marat5 commented on src/styles/styles.css
> +@font-face {
Может у меня кеши какие-то, но я вижу старые шрифты) Я так понимаю кирилицы у этого шрифта нет, а для латинских букв используется старый, так что этот нигде не видно) Или тут другая задумка?)

2021-07-30 10:40 UTC, vicpril commented on src/components/organisms/App/App.tsx
> +        {// Метод fetchData используется только в посреднике хранилища, в основном чтобы диспатчить перед рендером.
Теперь этот комментарий не актуален. Потому, что я перенес инициализацию хранилища в контроллер.
Исправлю, будет так:
```// Метод fetchData используется только при инициализации хранилища, в основном, чтобы диспатчить перед рендером```

2021-07-30 10:40 UTC, vicpril commented on src/routes/index.ts
> +    // темка будет темная - т.к. еще есть глобальный тестовый переключатель - testDispatchMiddleware.ts
Согласен выпилю

2021-07-30 10:58 UTC, vicpril commented on src/server/controllers/IndexController.tsx
> +        url.parse(location).pathname as string,
Почти. 
1. В методе routes some. Мы проходимся по всем роутам и останавливаемся, когда вернем `true`. Имитация работы Switch.
2. Метод matchPath сравнивает путь в локейшн (только часть - pathname) и полем `path` в текущем объекте `route`, так же как это делает `<Route />` - c параметрами. Если совпало, он генерит объект со свойствами идентичными свойствам Route, используя переданную строку и `route`. Опять же имитация Switch. Почитать можно [здесь](https://reactrouter.com/web/api/matchPath). Если не совпало тогда `null`
3. Дальше просто: если в `match` есть fetchData, то реализует его и складывает в массив промисов.
4. Если был match то цикл закончится. Если нет, то следующий роут.
5. Ждем пока выполняться все промисы из массива и рендерим.

2021-07-30 10:59 UTC, vicpril commented on src/server/controllers/IndexController.tsx
> +    // dispatch action END to close saga
Это от Моргунова) close я выпилил. Почищу

2021-07-30 11:00 UTC, vicpril commented on src/server/index.d.ts
> +            logger: () => void;
Раньше тут было описание типа Response. Теперь это не нужно - уберу

2021-07-30 11:03 UTC, vicpril commented on src/styles/styles.css
> +@font-face {
Странно. Я выпилю Russo One, но у меня и так работает
![image](https://user-images.githubusercontent.com/11062297/127643893-4b3c2ff1-0777-41c8-8f3f-846389a86267.png)

2021-07-30 11:09 UTC, vicpril commented on src/styles/styles.css
> +@font-face {
Хм... это потому, что он у меня в системе загружен был. А сайт не подтягивает. Предлагаю это в отдельную задачу вынести.

2021-07-30 13:01 UTC, DmitryKhitrin approved these changes

2021-07-31 03:37 UTC, merged